image: "rust:latest"

default:
  before_script:
    - rustc --version
    - cargo --version

stages:
  - test
  - release

test:cargo:
  script:
    - cargo test --workspace --verbose

lint-code:
  stage: test
  script:
    - rustup component add rustfmt
    - cargo fmt -- --check
    - rustup component add clippy
    - cargo clippy -- -D warnings

release:prepare:
  stage: release
  script:
    - cargo build --release
    - mkdir -p dist
    - cp target/release/osu_helper_script dist/osu_helper_script
  artifacts:
    paths:
      - dist/

release:create:
  stage: release
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_TAG == $CI_DEFAULT_BRANCH
  needs:
    - job: release:prepare
      artifacts: true
  release:
    name: "$CI_COMMIT_TAG"
    tag_name: "$CI_COMMIT_TAG"
    description: "$CI_COMMIT_TAG"
    assets:
      links:
        - link: "dist/osu_helper_script"
          name: "osu_helper_script"
          type: "binary"
