image: "rust:latest"

stages:
  - build

build:
  stage: build
  script:
    - cargo build

release_job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG # Run this job when a tag is created
  script:
    - cargo build --release
  release: # See https://docs.gitlab.com/ee/ci/yaml/#release for available properties
    tag_name: "$CI_COMMIT_TAG"
    description: "$CI_COMMIT_TAG"
    assets:
      links:
        - link: "target/release/osu_helper_script"
          name: "osu_helper_script"
          type: "binary"
