image: "rust:latest"

# Use cargo to test the project
test:cargo:
  rules:
    - if: $CI_COMMIT_TAG
      when: never 
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo test --workspace --verbose

release:cargo:
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - cargo build --release
    - cp target/release/osu_helper_script .
  artifacts:
    paths:
      - osu_helper_script
  release:
    tag_name: "$CI_COMMIT_TAG"
    description: "test"
    assets:
      links:
        - name: osu_helper_script
          url: ./osu_helper_script
