image: "rust:latest"

default:
  before_script:
    - rustc --version
    - cargo --version

stages:
  - test
  - prepare
  - release

test:cargo:
  script:
    - cargo test --workspace --verbose

lint-code:
  stage: test
  script:
    - rustup component add rustfmt
    - cargo fmt -- --check
    - rustup component add clippy
    - cargo clippy -- -D warnings

prepare_job:
  stage: prepare
  script:
    - cargo build --release
    - mkdir -p dist
    - cp target/release/osu_helper_script dist/osu_helper_script
  artifacts:
    paths:
      - dist/

release_job:
  stage: release
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH 
  needs:
    - job: prepare_job
      artifacts: true
  release:
    name: "$CI_COMMIT_TAG"
    tag_name: "$CI_COMMIT_TAG"
    description: "$CI_COMMIT_TAG"
    assets:
      links:
        - url: "./dist/osu_helper_script"
          name: "osu_helper_script"
