# !reference https://forum.gitlab.com/t/making-a-binary-release-via-ci-cd/57148/2

stages:
  - test
  - build
  - upload
  - release

variables:
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/osu_helper_script/${CI_COMMIT_TAG}"

  BIN_FILE_NAME: osu_helper_script-${CI_COMMIT_TAG}
  BIN_URL: ${PACKAGE_REGISTRY_URL}/${BIN_FILE_NAME}

  SOURCES_FILE_NAME: osu_helper_script-${CI_COMMIT_TAG}.tar.zst
  SOURCES_URL: ${PACKAGE_REGISTRY_URL}/${SOURCES_FILE_NAME}

test:
  stage: test
  image: "rust:latest"
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - rustc --version && cargo --version 
    - cargo test --workspace --verbose

build:
  stage: build
  image: "rust:latest"
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - cargo build --release
    - mkdir sources/completions -p
    - mv target/release/osu_helper_script sources/
    - mv target/release/tab_completions/_osu_helper_script sources/zsh
    - mv target/release/tab_completions/osu_helper_script.bash sources/bash
    - mv target/release/tab_completions/osu_helper_script.fish sources/fish
  cache:
    paths:
      - target/release/
  artifacts:
    paths:
      - sources

upload:
    stage: upload
    image: alpine
    rules:
      - if: $CI_COMMIT_TAG
    script:
      - apk add curl tar zstd
      - tar --zstd -cvf "sources.tar.zst" -C sources/ .
      - 'curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file sources/osu_helper_script ${BIN_URL}'
      - 'curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file sources.tar.zst ${SOURCES_URL}'

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "running release_job for $TAG"
  release:
    name: ${CI_COMMIT_TAG}
    tag_name: ${CI_COMMIT_TAG}
    description: "Check and compare commit histories for changes."
    assets:
      links:
        - name: ${BIN_FILE_NAME}
          url: ${BIN_URL}
        - name: ${SOURCES_FILE_NAME}
          url: ${SOURCES_URL}