[package]
name = "osu_helper_script"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
chrono = "0.4.25"
clap = { version = "4.3.0", features = ["derive"] }
indicatif = "0.17.5"
inquire = "0.6.2"
md5 = "0.7.0"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
ureq = { version = "2.6.2", features = ["json"] }
