name: Release
on:
    push:
        tags:
            - "v*.*.*"

permissions:
    contents: write
    discussions: write

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: dtolnay/rust-toolchain@stable

            - name: Build
              run: cargo build --release

            - name: Install post-build dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y tar zstd

            - name: Move tab completion files
              run: |
                  mkdir -p sources/completions
                  mv target/release/osu-helper-script sources/
                  mv target/release/tab_completions/_osu-helper-script sources/completions/zsh
                  mv target/release/tab_completions/osu-helper-script.bash sources/completions/bash
                  mv target/release/tab_completions/osu-helper-script.fish sources/completions/fish

            - name: Package sources directory with tar.zst
              run: tar --zstd -cvf "sources.tar.zst" -C sources/ .

            - name: Checksum values for binary and sources
              run: |
                  sha256sum sources.tar.zst > sha256_sources.txt
                  sha256sum sources/osu-helper-script > sha256_osu-helper-script.txt
                  echo "SHA256 for sources.tar.zst: $(cat sha256_sources.txt)" > BODY.txt
                  echo "SHA256 for osu-helper-script: $(cat sha256_osu-helper-script.txt)" >> BODY.txt

            - name: Create release
              uses: softprops/action-gh-release@v1
              with:
                  body_path: ./BODY.txt
                  files: |
                      sources/osu-helper-script
                      sources.tar.zst
